### ISSUE TITLE
Release NPM

### ISSUE THREAD

**Issue by tontonAurel** [json-schema-form/angular-schema-form-material#15]
Hey,

could you please make a release and a npm package.

thanks

**Comment by Anthropic** [comment]
@tontonAurel I will take a look this weekend and give it a go, hadn't thought much about it given it isn't complete other than some basic field types, but of course it always helps to get feedback early on.

**Comment by Anthropic** [comment]
@tontonAurel sorry for the delay, I will get to it soon

**Comment by Anthropic** [comment]
@tontonAurel Done, needs a lot of work still, but alpha 1 is available if you want to try it out. Bower is released also.
