### ISSUE TITLE
Bower registry problem

### ISSUE THREAD

**Issue by juanmav** [json-schema-form/angular-schema-form-material#16]
Hi, all.

I just noticed bower has a reference to another repo (just a copy from this one but outdated):

http://bower.io/search/?q=angular-schema-form-material

Any chance to fix it ? Because is very confusing.

Thanks in advance
JM

**Comment by Anthropic** [comment]
@juanmav thanks again, looks like someone cloned this repo, renamed it, but then submitted it as theirs to Bower, not sure why, but shouldn't be hard to sort out, I've tried email, but may have to go direct to Bower if I don't get a response.

**Comment by Anthropic** [comment]
@juanmav FYI https://github.com/bower/registry/issues/192 so I will close this issue here :)

**Comment by Anthropic** [comment]
Thanks for acting during my slumber @juanmav, so now how do we transfer it?

**Comment by juanmav** [comment]
@Anthropic, it isn't necessary any kind of transfer. I registered this repository:

http://bower.io/search/?q=angular-schema-form-material

Bower doesn't use auth/users to register repositories, so you can register repositories for other people if you want, like I did.

**Comment by Anthropic** [comment]
@juanmav ah right thank you very much :)
