### ISSUE TITLE
What would be the best way to integrate it into my existing angularjs ?

### ISSUE THREAD

**Issue by marvinosswald** [json-schema-form/angular-schema-form-material#2]
I would like to contribute and use it at the same time..

**Comment by davidlgj** [comment]
Hi @marvinosswald 

awesome! We're happy to get help. I just answered the same question here: https://github.com/Textalk/angular-schema-form/issues/506#issuecomment-145594816

TL:DR;
Start doing a form type that's missing by looking on how it's done in the new bootstrap decorator: https://github.com/Textalk/angular-schema-form-bootstrap

You can do a "work-in-progress" PR to let us all know what you're working on and to get early feedback :)

**Comment by marvinosswald** [comment]
Thought it would be a good start using the develop branch of this repo but getting an error just by trying whats already there...

it looks like decorator isn't defined..
[Line 199 in builder.js](https://github.com/Textalk/angular-schema-form/blob/f8be594bdabe66ad3aa003a429a0b7de0838a9ed/src/services/builder.js#L199)

```
TypeError: Cannot read property 'text' of undefined
at http://localhost:8000/js/vendor.js:80060:30
at Array.reduce (native)
at angular.module.provider.sfPathProvider.$get.build (http://localhost:8000/js/vendor.js:80053:13)
at Object.angular.module.provider.sfPathProvider.$get.sfPath.build (http://localhost:8000/js/vendor.js:80130:16)
at angular.module.directive.sfBuilder.link.internalRender (http://localhost:8000/js/vendor.js:82346:44)
at angular.module.directive.sfBuilder.link.render (http://localhost:8000/js/vendor.js:82308:13)
at Object.<anonymous> (http://localhost:8000/js/vendor.js:82391:13)
at Scope.parent.$get.Scope.$digest (http://localhost:8000/js/vendor.js:15818:40)
at Scope.parent.$get.Scope.$apply (http://localhost:8000/js/vendor.js:16097:24)
at done (http://localhost:8000/js/vendor.js:10546:47)
```

**Comment by davidlgj** [comment]
@marvinosswald that strange... I tried the demo `example/material-example.js` just to make sure and it works (To try it out first checkout the material repo, do a `bower install` and start up a server, like `http-server`)

How do you include ASF and the material decorator? In what order?

**Comment by marvinosswald** [comment]
@davidlgj pretty sure it's because how i wire my angular app.. got a new error 

using (installed with bower):
- angular-schema-form#development (if I use the normal master branch it just uses the bootstrap-decorator)
- https://github.com/Textalk/angular-schema-form-material.git#develop

```
[Error] Error: undefined is not an object (evaluating 'decorator[f.type]')
http://localhost:8000/js/vendor.js:80060:30
reduce@[native code]
build@http://localhost:8000/js/vendor.js:80053:19
build@http://localhost:8000/js/vendor.js:80130:21
internalRender@http://localhost:8000/js/vendor.js:82346:49
render@http://localhost:8000/js/vendor.js:82308:27
http://localhost:8000/js/vendor.js:82391:19
$digest@http://localhost:8000/js/vendor.js:15818:43
$apply@http://localhost:8000/js/vendor.js:16097:31
done@http://localhost:8000/js/vendor.js:10546:53
completeRequest@http://localhost:8000/js/vendor.js:10744:15
requestLoaded@http://localhost:8000/js/vendor.js:10685:24
    (anonyme Funktion) (vendor.js, line 12477)
    (anonyme Funktion) (vendor.js, line 9246)
    $digest (vendor.js, line 15844)
    $apply (vendor.js, line 16097)
    done (vendor.js, line 10546)
    completeRequest (vendor.js, line 10744)
    requestLoaded (vendor.js, line 10685)
```

**Comment by davidlgj** [comment]
Right now the material decorator re-uses the same module as ASF (which it probably shouldn't) so you need to include it _after_ ASF or else it has no module.

**Comment by marvinosswald** [comment]
thought i would do so but maybe is gulp mixin stuff up.. 

And I think angular-schema-form-material should have the development branch of ASF as dependency because otherwise bootstrap-decorator is still included, don't you think ?

**Comment by marvinosswald** [comment]
got it :D indeed it was gulp mixing stuff up

**Comment by davidlgj** [comment]
Awesome! 

It's just a temporary thing that you get the old bootstrap decorator. I'm gearing up for a new release with it removed. Just need to get the docs in order. And I wouldn't want to give the impression that you _need_ the development branch of ASF to use the material decorator.  Also the development branch is a bit unstable sometimes and should be used for development only.

**Comment by marvinosswald** [comment]
@davidlgj alright then :+1:

**Comment by Anthropic** [comment]
I assume this is sorted now so I'll close the issue, let @davidlgj or I know if you need more help with it.
