### ISSUE TITLE
How to extend this decorator

### ISSUE THREAD

**Issue by drtobal** [json-schema-form/angular-schema-form-material#32]
Hi,
How can I extend this decorator with my own custom components?
thanks.

**Comment by Anthropic** [comment]
@drtobal if you want a new field type you can make an add-on, if you want to make multiple or change the current fields at all then easiest to copy this one and alter it. Extending is planned in future using the builder functions, but not at this stage.

Please re-open if you do not feel the question has been answered sufficiently :)

**Comment by drtobal** [comment]
@dvelasquez
